#! /bin/sh

bspc config border_width        1
bspc config window_gap         10

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding		16

# bspc config normal_boder_color		"#777777"
bspc config focused_border_color	"#aaaaaa"

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d www ws ide o V VI VII VIII IX X


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a monodevelop desktop=^3
bspc rule -a NetBeans desktop=^3
bspc rule -a LibreOffice desktop=^4
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off

sxhkd &
urxvt &

# panel &
